plugin {
  hypreact {
    config_path = ~/.config/hypreact
    layout =
    default_layout = first

    workspace_layout = 1,master-stack
    workspace_layout = 2,columns
    workspace_layout = special:scratch,floating

    monitor_layout = DP-1,wide
    monitor_layout = HDMI-A-1,stack
  }
}
